apiVersion: apps/v1
kind: Deployment
metadata: 
  name: service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: service
  template:
    metadata:
      labels:
        run: service
    spec:
      containers: 
      - name: service
        image: 162.168.2.141:1180/middle/service:1.0.0
        imagePullPolicy: IfNotPresent
        command: ["java"]
        args: ["-Xbootclasspath/a:/config", "-jar", "/usr/local/app.jar"]
        volumeMounts:
          - name: config
            mountPath: /config
          - name: logs
            mountPath: /logs
        ports: 
        - containerPort: 9002
          protocol: TCP
      volumes:
        - name: config
          configMap:
            name: service
        - name: logs
          hostPath:
            path: /home/docker/middle/logs

---
apiVersion: v1
kind: Service
metadata: 
  name: service
  labels: 
    run: service
spec: 
  type: Nodeport
  ports: 
  - port: 38080
    nodePort: 31002
    targetPort: 9002
    protocol: TCP
  selector: 
    run: service

