spring:
  application:
    name: service
  zipkin:
    base-url: http://127.0.0.1:9003
  sleuth:
    sampler:
      probability: 1

server:
  port: 9002
#  servlet:
#    context-path: /service


logging:
  level:
    root: info
  path: /logs/${spring.application.name}-logs
  config: classpath:logback-core.xml

