spring:
  application:
    name: service
server:
  port: 9002
#  servlet:
#    context-path: /service


logging:
  level:
    root: info
  path: /logs/${spring.application.name}-logs
  config: classpath:logback-core.xml

