package com.sinovatio.mapp.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sinovatio.mapp.entity.DeviceFactoryEntity;

import com.sinovatio.mapp.greendao.DeviceFactoryEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig deviceFactoryEntityDaoConfig;

    private final DeviceFactoryEntityDao deviceFactoryEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        deviceFactoryEntityDaoConfig = daoConfigMap.get(DeviceFactoryEntityDao.class).clone();
        deviceFactoryEntityDaoConfig.initIdentityScope(type);

        deviceFactoryEntityDao = new DeviceFactoryEntityDao(deviceFactoryEntityDaoConfig, this);

        registerDao(DeviceFactoryEntity.class, deviceFactoryEntityDao);
    }
    
    public void clear() {
        deviceFactoryEntityDaoConfig.clearIdentityScope();
    }

    public DeviceFactoryEntityDao getDeviceFactoryEntityDao() {
        return deviceFactoryEntityDao;
    }

}
