spring:
  application:
    name: web
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
  zipkin:
    base-url: http://trace/
    #使用服务发现
    #discoveryClientEnabled: true
    #当前服务名称，不写默认取spring.application.name
    #service:
      #name: consumer02-sleuth
  sleuth:
    sampler:
      probability: 1

server:
  port: 9001
  servlet:
    context-path: /preweb

logging:
  level:
    root: info
  path: /logs/${spring.application.name}-logs
  config: classpath:logback-core.xml

resources: # 指定静态资源的路径
  static-locations: classpath:/static/,classpath:/views/
  cache-period: 0

service:
  gateway: gateway
  web: web
  service: service