spring:
  application:
    name: gateway
  zipkin:
    base-url: http://127.0.0.1:9003
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: web
          uri: http://127.0.0.1:9001
          order: 0
          predicates:
            - Path=/preweb/**
          filters:
            - StripPrefix=0
        - id: service
          uri: http://127.0.0.1:9002
          order: 1
          predicates:
            - Path=/preservice/**
          filters:
            - StripPrefix=1

server:
  port: 9000

logging:
  level:
    root: info
  path: /logs/${spring.application.name}-logs
  config: classpath:logback-core.xml


service:
  gateway: 127.0.0.1:9000
  web: 127.0.0.1:9001/notweb
  service: 127.0.0.1:9002
