spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: webc
#          uri: http://localhost:9000
          uri: lb://web
          order: 0
          predicates:
            - Path=/webc/**
          filters:
            - StripPrefix=1


server:
  port: 9000

logging:
  level:
    root: info
  path: /logs/${spring.application.name}-logs
  config: classpath:logback-core.xml