spring:
  application:
    name: web
server:
  port: 9001
  servlet:
    context-path: /web


logging:
  level:
    root: info
  path: /logs/${spring.application.name}-logs
  config: classpath:logback-core.xml