FROM 10.45.136.151:1180/middle/jdk:1.8.0_144

# copy app jar into container
COPY gateway-*.jar /usr/local/app.jar

# open port
#EXPOSE 8080

#VOLUME /data

# start app service when container running 
#CMD java -Xbootclasspath/a:/etc/app/ -jar /usr/local/app.jar
