spring:
  application:
    name: web
server:
  port: 9001


logging:
  level:
    root: info
  path: /logs/${spring.application.name}-logs
  config: classpath:logback-core.xml


service:
  gateway: 127.0.0.1:9000
  web: 127.0.0.1:9001
  service: 127.0.0.1:9002