spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: web
          uri: lb://web
          order: 0
          predicates:
            - Path=/webweb/**
          filters:
            - StripPrefix=0
        - id: service
          uri: lb://service
          order: 1
          predicates:
            - Path=/service/**
          filters:
            - StripPrefix=1


server:
  port: 9000

logging:
  level:
    root: info
  path: /logs/${spring.application.name}-logs
  config: classpath:logback-core.xml


service:
  gateway: gateway
  web: web
  service: service