spring:
  application:
    name: gateway
  zipkin:
    base-url: http://trace/
      #使用服务发现
      #discoveryClientEnabled: true
      #当前服务名称，不写默认取spring.application.name
      #service:
    #name: consumer02-sleuth
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: web
          uri: lb://web
          order: 0
          predicates:
            - Path=/preweb/**
          filters:
            - StripPrefix=0
        - id: service
          uri: lb://service
          order: 1
          predicates:
            - Path=/preservice/**
          filters:
            - StripPrefix=1


server:
  port: 9000

logging:
  level:
    root: info
  path: /logs/${spring.application.name}-logs
  config: classpath:logback-core.xml


service:
  gateway: gateway
  web: web
  service: service